name = "StanfordAA228V"
uuid = "6f6e590e-f8c2-4a21-9268-94576b9fb3b1"
authors = ["Robert Moss <rmoss92@gmail.com>"]
version = "0.1.27"

[deps]
AbstractPlutoDingetjes = "6e696c72-6542-2067-7265-42206c756150"
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GridInterpolations = "bb4c363b-b914-514b-8517-4eb369bc008a"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LazySets = "b4f0291d-fe17-52bc-9479-3d1a343d9043"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
ProgressLogging = "33c8b6b6-d38a-422a-b730-caa89a2f386c"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SignalTemporalLogic = "a79a9ddd-d50e-4d85-a979-5d85760e62a0"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
AbstractPlutoDingetjes = "1.3.2"
BSON = "0.3"
Base64 = "1.11.0"
Distances = "0.10.12"
Distributions = "0.25"
Downloads = "1.6.0"
ForwardDiff = "0.10"
GridInterpolations = "1"
Interpolations = "0.15.1"
LazySets = "2, 3.0.0"
LinearAlgebra = "1"
Markdown = "1.11.0"
Optim = "1.10"
Parameters = "0.12"
Pkg = "1.11.0"
Plots = "1.40"
Pluto = "0.20"
PlutoUI = "0.7"
ProgressLogging = "0.1.4"
SignalTemporalLogic = "0.1, 1"
TOML = "1.0.3"
julia = "1"

[workspace]
projects = ["test"]
